name: Build Builder binary

on:
  workflow_dispatch:
    inputs:
      branch:
        # description: 'invoke real vs mock prover (with or without root)'
        # required: true
        # default: 'sub_mock_prover'
        # type: choice
        # options:
        # - sub_real_prover
        # - sub_mock_prover
        # - root_mock_prover
        # - root_real_prover

# env:
#   CGO_CFLAGS_ALLOW: "-O -D__BLST_PORTABLE__"
#   CGO_CFLAGS: "-O -D__BLST_PORTABLE__"

jobs:

   build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.20
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: make geth

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: geth
        path: build/bin/geth
    
    - name: List Artifacts
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ github_repository }}/actions/artifacts
